@Restaurants.API_HostAddress = http://localhost:5001
# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/4

###

@id=4
GET {{Restaurants.API_HostAddress}}/api/Restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "Sushi Master",
  "description": "Fresh and authentic Japanese sushi",
  "hasDelivery": false,
  "categoryId":9,
  "contactEmail": "infosushimaster.jp",
  "contactNumber": "555-123-4567",
  "street": "456 Oak Avenue",
  "city": "Los Angeles",
  "postalCode": "90-01"
}
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/9

###

PUT {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "id": 4,
  "name": "Sushi Daily ==",
  "description": "Authentic Japanese sushi and sashimi made fresh daily with premium ingredients.",
  "hasDelivery": true,
  "categoryId": 3,
  "contactEmail": "contact@kfc.com",
  "contactNumber": "01228616700",
  "street": "New St 78",
  "city": "Birmingham",
  "postalCode": "12-434",
  "category": null,
  "dishes": [],
  "createdAt": "2026-02-11T19:51:10.9372045",
  "updatedAt": null
}

###
